name: blackbox_codegen
description: Code generator for blackbox_core boxes (MobX-style) with optional ObservableBox projection.
version: 0.0.2
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
resolution: workspace

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.4
  source_gen: ^4.2.0

  blackbox_annotations: ^0.2.0

dev_dependencies:
  build_runner: ^2.10.5
  lints: ^6.1.0
