name: blackbox_example
description: Blackbox codegen example with sync/async boxes
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  blackbox: ^0.0.5

  blackbox_flutter: ^0.0.2

  blackbox_annotations: ^0.0.2

dev_dependencies:
  build_runner: ^2.10.5

  blackbox_codegen: ^0.0.2

flutter:
  uses-material-design: true
